name: Docker UI build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses:  actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Buiil Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: leddit-ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image test
        run: |
          docker images
